### ISSUE TITLE
UR10 Issues

### ISSUE THREAD

**Issue by egekorkan** [tum-esi/wot-sys#10]
During the merge of #7, we have identified some issues that need to be fixed:

- [x] The check for the status of the robot should be done via the getRobotSafetyStatus (https://sdurobotics.gitlab.io/ur_rtde/api/api.html#_CPPv4N7ur_rtde20RTDEReceiveInterface19getSafetyStatusBitsEv)
- [x] The gripper is not working. If there is any kind of program running in the robot via the teaching pendant, the program execution seems to be blocked, making it impossible to send any rtde commands

**Comment by FadySalama** [comment]
This has been fixed by the latest [commit ](https://github.com/tum-esi/wot-sys/commit/74521fc54331026d7d9135914f58fc0fad01a353)
