### ISSUE TITLE
Dobot issues

### ISSUE THREAD

**Issue by egekorkan** [tum-esi/wot-sys#6]
At https://github.com/tum-esi/wot-sys/blob/cc2a03c5119de4220b7afd54072fe33a6d3567aa/Devices/flask-dobot-magician/lib/tdGenerator.py#L23 there is min and max used but they should be actually minimum and maximum and have number values

**Comment by egekorkan** [comment]
Also, the push to click is not handled properly, i.e. the robot only pushes once and thinks that there was a click

**Comment by FadySalama** [comment]
I think this is already resolved now
